spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show_sql: false